version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: backend:${BACKEND_VERSION:-latest}
    restart: always
    env_file:
    - .env
