from typing import List, Optional
from fastapi import Depends
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from backend.db.dependencies import get_db_session
from backend.db.models.explained_image_model import ExplainedImageModel
from backend.models.explained_image import ExplainedImage

class ExplainedImageDAO:
    """Class for accessing the explained_images table."""

    def __init__(self, session: AsyncSession = Depends(get_db_session)):
        self.session = session

    async def create_explained_image(
        self,
        explained_image: ExplainedImage,
    ) -> None:
        """
        Add single explained image to session.

        :param image: URL or identifier of the image.
        :param comment: Optional comment about the image.
        :param date: Optional date associated with the image.
        :param latitude: Optional latitude where the image was taken.
        :param longitude: Optional longitude where the image was taken.
        :param altitude: Optional altitude where the image was taken.
        :param location: Optional location information.
        :param direction: Optional direction information.
        :param ai_comment: Optional comment generated by AI.
        :param ai_comment_vector: Optional vector representation of the AI comment.
        """
        explained_image = ExplainedImageModel(
            image=explained_image.image,
            comment=explained_image.comment,
            date=explained_image.date,
            latitude=explained_image.latitude,
            longitude=explained_image.longitude,
            altitude=explained_image.altitude,
            location=explained_image.location,
            direction=explained_image.direction,
            ai_comment=explained_image.ai_comment,
            ai_comment_vector=explained_image.ai_comment_vector,
        )
        self.session.add(explained_image)

    async def get_all_explained_images(
        self, limit: int, offset: int
    ) -> List[ExplainedImageModel]:
        """
        Get all explained image models with limit/offset pagination.

        :param limit: limit of explained images.
        :param offset: offset of explained images.
        :return: stream of explained images.
        """
        raw_explained_images = await self.session.execute(
            select(ExplainedImageModel).limit(limit).offset(offset),
        )

        return list(raw_explained_images.scalars().fetchall())

    async def filter(
        self, image: Optional[str] = None, comment: Optional[str] = None
    ) -> List[ExplainedImageModel]:
        """
        Get specific explained image model.

        :param image: URL or identifier of the image.
        :param comment: Comment associated with the image.
        :return: explained image models.
        """
        query = select(ExplainedImageModel)
        if image:
            query = query.where(ExplainedImageModel.image == image)
        if comment:
            query = query.where(ExplainedImageModel.comment == comment)
        rows = await self.session.execute(query)
        return list(rows.scalars().fetchall())
